### ISSUE TITLE
Query variables are not validated

### ISSUE THREAD

**Issue by wiktor256** [graph-gophers/graphql-go#292] opened 2018-11-20 16:25 UTC
There seems to be a bug in schema validation of query variables.
For this schema:

```
input SearchFilter {
  required: String!
  optional: String
}

type SearchResults {
  match: String
}

type Query {
  search(filter: SearchFilter!): [SearchResults!]!
}
```

the following query correctly fails schema validation:
```
 query  {
   search(filter: {}) {
     match
   }
} 
```
with the error message:
```
{
  "errors": [
    {
      "message": "Argument \"filter\" has invalid value {}.\nIn field \"required\": Expected \"String!\", found null.",
      "locations": [
        {
          "line": 2,
          "column": 17
        }
      ]
    }
  ]
}
```

but the same query using variables doesn't fail at all:

```
query s($filter:SearchFilter!) {
  search(filter: $filter){
    match
  }
}

variables:
{
  "filter": {}
}
```

**Comment by pavelnikolov** [comment] 2018-11-30 00:21
Hi @wiktor256, thank you for reporting this issue!
PRs are welcome!

**Comment by xiaocode** [comment] 2019-03-10 02:08
I found the same bug too.+1.

**Comment by suessflorian** [comment] 2021-10-02 02:32
I'll give this one a crack 👍

**Comment by suessflorian** [comment] 2021-10-02 03:40
Interesting, I'm having struggle to reproduce this example as I was trying to write tests to reproduce this issue - then went to a minimal server example;

```go
package main

import (
	"context"
	"log"
	"net/http"

	"github.com/graph-gophers/graphql-go"
	"github.com/graph-gophers/graphql-go/relay"
)

type queryVarResolver struct{}
type filterArgs struct {
	Required string
	Optional *string
}
type filterSearchResults struct {
	Match *string
}

func (r *queryVarResolver) Search(ctx context.Context, args *struct{ Filter filterArgs }) []filterSearchResults {
	return []filterSearchResults{}
}

func main() {
	schema := graphql.MustParseSchema(`
        input SearchFilter {
          required: String!
          optional: String
        }

        type SearchResults {
          match: String
        }

        type Query {
          search(filter: SearchFilter!): [SearchResults!]!
        }
      `, &queryVarResolver{}, graphql.UseFieldResolvers())
	http.Handle("/query", &relay.Handler{Schema: schema})
	log.Fatal(http.ListenAndServe(":8080", nil))
}
```

Mod file;
```go
module test

go 1.16

require (
	github.com/graph-gophers/graphql-go v1.2.0
	github.com/stretchr/testify v1.7.0 // indirect
)
```

Running this bad boy, I attempt to retry this query
```graphql
query s($filter:SearchFilter!) {
  search(filter: $filter){
    match
  }
}
```

With variables
```json
{
  "filter": {}
}
```

Which using `curl` looks like
```sh
curl --request POST \
  --url http://localhost:8080/query \
  --data '{"query":"query s($filter:SearchFilter!) {\n  search(filter: $filter){\n    match\n  }\n}","variables":{"filter":{}},"operationName":"s"}'
```

Yielding the response;
```json
{
  "errors": [
    {
      "message": "Variable \"required\" has invalid value null.\nExpected type \"String!\", found null.",
      "locations": [
        {
          "line": 3,
          "column": 11
        }
      ]
    }
  ]
}
```

Which is exactly as expected.

---

I wonder if perhaps there is an issue in your graphQL clients @xiaocode and @wiktor256

**Comment by suessflorian** [comment] 2021-10-02 03:41
I do think though with this evidence we can close this as an issue @pavelnikolov 👍

**Comment by suessflorian** [comment] 2021-10-02 03:50
(and just for fun, some tests for `Exec` here;

```go
type queryVarResolver struct{}
type filterArgs struct {
	Required string
	Optional *string
}
type filterSearchResults struct {
	Match *string
}

func (r *queryVarResolver) Search(ctx context.Context, args *struct{ Filter filterArgs }) []filterSearchResults {
	return []filterSearchResults{}
}

func TestQueryVariablesValidation(t *testing.T) {
	gqltesting.RunTests(t, []*gqltesting.Test{
		{
			Schema: graphql.MustParseSchema(`
        input SearchFilter {
          required: String!
          optional: String
        }

        type SearchResults {
          match: String
        }

        type Query {
          search(filter: SearchFilter!): [SearchResults!]!
        }
      `, &queryVarResolver{}, graphql.UseFieldResolvers()),
			Query: `
        query {
          search(filter: {}) {
            match
          }
        }
      `,
			ExpectedErrors: []*gqlerrors.QueryError{{
				Message: "Argument \"filter\" has invalid value {}.\nIn field \"required\": Expected \"String!\", found null.",
				Locations: []gqlerrors.Location{{Line: 3, Column: 26}},
        Rule: "ArgumentsOfCorrectType",
			}},
		},
    {
			Schema: graphql.MustParseSchema(`
        input SearchFilter {
          required: String!
          optional: String
        }

        type SearchResults {
          match: String
        }

        type Query {
          search(filter: SearchFilter!): [SearchResults!]!
        }
      `, &queryVarResolver{}, graphql.UseFieldResolvers()),
			Query: `
        query q($filter: SearchFilter!) {
          search(filter: $filter) {
            match
          }
        }
      `,
      Variables: map[string]interface{}{"filter": map[string]interface{}{}},
			ExpectedErrors: []*gqlerrors.QueryError{{
				Message: "Variable \"required\" has invalid value null.\nExpected type \"String!\", found null.",
				Locations: []gqlerrors.Location{{Line: 3, Column: 11}},
        Rule: "VariablesOfCorrectType",
			}},
    },
	})
}
```

**Closed** 2021-10-05 08:40 UTC
Labels: help wanted
