### ISSUE TITLE
Get queried properties in the current request

### ISSUE THREAD

**Issue by fuintis** [graph-gophers/graphql-go#280] opened 2018-10-26 00:11 UTC
Is there a way within resolvers functions to get the properties requested by the client?

This feature sounds very useful to implement a mechanism that allow to fine tuning, say, a DB query with only a required data.

Anyone knows about this?

Many thx in advance.

**Comment by pavelnikolov** [comment] 2018-11-30 00:35
There has been such requests in the past. I'll close this issue as a duplicate of #17 
The easiest workaround is to use a dynamic resolver with a Golang chan, which blocks until the field has been provided. It'll only call the fields that have been requested. The downside is that you'll not know the fields in advance.
You can also take a look at the example [dataloader](https://github.com/graph-gophers/dataloader) that @tonyghita has written.

**Closed by pavelnikolov** 2018-11-30 00:35 UTC

**Comment by lfv89** [comment] 2019-01-21 17:08
Hey @pavelnikolov 

Quick question, how could dataloader help in this case?

If I understand correctly, dataloader helps by avoiding `n + 1` queries by batching results. Does it really could help reducing the amount of fields returned by a specific query as well? If so, how could we pass to it which fields to return?

**Comment by pavelnikolov** [comment] 2019-01-21 22:03
The dataloader doesn't reduce the number of fields being queried AFAIK.

**Comment by lfv89** [comment] 2019-01-22 12:32
Thanks @pavelnikolov 

If that's the case then, could be so kind to to elaborate more on what you said earlier about the workaround using a dynamic resolver? A solution for this problem highly interests us.

**Comment by pavelnikolov** [comment] 2019-01-22 22:06
I haven't thought on how to get a particular subset of fields from a DB 🤔
