### ISSUE TITLE
schema.Exec doesn't return partial data on error

### ISSUE THREAD

**Issue by IceeMC** [graph-gophers/graphql-go#463] opened 2021-07-02 00:24 UTC
So, basically my problem is that, if I do a query like.
Take note that, testAuth strictly requires the user to be authenticated, and if they aren't it returns an error for that resolver.

```graphql
query {
  testAuth
  doesNotNeedAuth
}
```

Now, the response I get is:
```json
{
  "errors": [
    {
      "message": "you are not authenticated",
      "path": [
        "testAuth"
      ]
    }
  ],
  "data": null
}
```

I expected a response like: 
```json
{
  "errors": [
    {
      "message": "you are not authenticated",
      "path": [
        "testAuth"
      ]
    }
  ],
  "data": {
    "doesNotNeedAuth": "Hello, world!"
  }
}
```

Now, if any of the resolvers that should return valid data return nothing (and the other ones do as well, i.e 2 resolvers returning null): a response should be the first code block above.

Pretty much, I would still like to see valid resolvers that return valid data being put into the data object, and errors being in the errors array, to prevent multiple queries. I know that other golang graphql libraries support this, but I migrated to this one because of the simplicity it was to use.

**Comment by pavelnikolov** [comment] 2021-07-02 09:05
Interested to see what does the spec say in this particular case?

**Comment by tonyghita** [comment] 2021-07-02 15:42
If the `testAuth` field is non-null and it errors, the error must propagate up to `data`—the nearest non-nullable parent.

http://spec.graphql.org/draft/#sec-Handling-Field-Errors

Check your schema definition to ensure you're not guaranteeing data will be there when you cannot guarantee it.

**Comment by pavelnikolov** [comment] 2021-07-02 15:54
@IceeMC I'm closing this issue as it seems like an issue with your schema. We have extensive tests for the error propagation of this library. Let me know if you still think that the problem is with the library.

**Closed by pavelnikolov** 2021-07-02 15:54 UTC
