### ISSUE TITLE
Error location and path for custom type UnmarshalGraphQL

### ISSUE THREAD

**Issue by yuzhoumao** [graph-gophers/graphql-go#352] opened 2019-09-26 10:39 UTC
We have custom types and corresponding unmarshal functions where the input is validated against the custom type definition

```go
// Hash represents the 32 byte Keccak256 hash of arbitrary data.
type Hash [HashLength]byte

// UnmarshalGraphQL unmarshals the provided GraphQL query data.
func (h *Hash) UnmarshalGraphQL(input interface{}) error {
    var err error
    switch input := input.(type) {
    case string:
        err = h.UnmarshalText([]byte(input))
    default:
        err = fmt.Errorf("Unexpected type for Bytes32: %v", input)
     }
    return err
}
```

When the user's query input is not valid for the custom type, error is returned. However, no location / path information is available when the query returns (copying directly from ethereum/go-ethereum#20042):

> The query 
> ```graphql
> {
>  block(hash: 99) {
>    hash
>  }
>}
> ```
> results in 
> ```json
> {
>  "errors": [
>    {
>      "message": "Unexpected type for Bytes32: 99"
>    }
>  ],
>  "data": {}
> }
>```

Ideally we can have locations and path information when the input argument for this custom type is not valid
```json
{
  "errors": [
    {
      "message": "Unexpected type for Bytes32: 99",
      "locations": [ { "line": 2, "column": 15 } ],
      "path": [ "block", "hash" ]
    }
  ]
}
```

**Comment by pavelnikolov** [comment] 2020-04-19 18:46
I am closing the issue as I am unable to reproduce it. See my comment on the linked PR. Let me know if I am missing something.

**Closed by pavelnikolov** 2020-04-19 18:46 UTC
