### ISSUE TITLE
Introspection must provide input type for arguments

### ISSUE THREAD

**Issue by romshark** [graph-gophers/graphql-go#167] opened 2018-02-14 13:37 UTC
I'm trying to use our [graphql-go](https://github.com/neelance/graphql-go/) based API in combination with [Graphcools GraphQL Playground](https://github.com/graphcool/graphql-playground) and [GraphiQL](https://github.com/graphql/graphiql) and I'm getting the following error in both:

`Introspection must provide input type for arguments.`

The documentation obviously doesn't work, though the schema compiles and runs just fine, queries work like a charm, just the introspection seems to be broken.

**Comment by tonyghita** [comment] 2018-02-14 16:12
I think this may have to do with the recent changes to the specification not being implemented in this library yet.

**Comment by romshark** [comment] 2018-02-27 21:05
Any chance it'll be fixed in the near future?

**Comment by romshark** [comment] 2018-04-07 11:53
Not yet, as far as I can remember I couldn't get the newest versions of [GraphiQL](https://github.com/graphql/graphiql) and [GraphQL Playground](https://github.com/graphcool/graphql-playground) to work with this library. Introspection didn't work at all throwing the error described above.

**Comment by tonyghita** [comment] 2018-04-07 14:36
Okay, if you get the chance to post the error it'd be super helpful! I'll take a shot a reproducing the issue myself.

**Comment by mwilli31** [comment] 2018-05-15 03:27
Is this issue still open?  I am getting a similar error:

```
Error: Introspection must provide input type for arguments.
    at invariant (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:25010:11)
    at getInputType (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:31071:29)
    at buildInputValue (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:31210:16)
    at https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:25140:31
    at Array.reduce (<anonymous>)
    at keyValMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:25139:15)
    at buildInputValueDefMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:31204:36)
    at fields (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:31185:16)
    at resolveThunk (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:28097:40)
    at GraphQLInputObjectType._defineFieldMap (https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.11.11/graphiql.js:28607:20)
```

Any idea what a fix for this would be?  It just started occurring for me.

**Comment by BlindingDark** [comment] 2018-06-13 12:32
since it can't use `Object Types` in `Input Types`.
but when I use a list of `Object Types` in `Input Types`, then I get the error`Introspection must provide input type for arguments.`

**Comment by pavelnikolov** [comment] 2023-02-14 10:28
@romshark I'm closing this issue due to inactivity. I'm not able to reproduce it locally.

**Closed by pavelnikolov** 2023-02-14 10:28 UTC
