### ISSUE TITLE
__typename field not merging correctly

### ISSUE THREAD

**Issue by gusmin** [graph-gophers/graphql-go#365] opened 2019-11-06 11:33 UTC
Sending this following query to the example starwars server:

![image](https://user-images.githubusercontent.com/33810377/68291254-c131b000-0089-11ea-9382-51c2de1f22e6.png)

Result to the following response containing several `__typename` fields while these ones should probably be merged instead:

![image](https://user-images.githubusercontent.com/33810377/68291212-aa8b5900-0089-11ea-8870-75a19b54ccc0.png)

**Comment by pavelnikolov** [comment] 2019-11-08 01:43
I'm unable to reproduce your error. I get this:
```
{
  "errors": [
    {
      "message": "graphql: panic occurred: {{\"Character\" {',' '\\x13'}}} does not implement \"Droid\""
    }
  ]
}
```

When I change `... on Droid` to `... on Character` the field `__typename` gets merged correctly.

**Closed by pavelnikolov** 2019-11-08 01:43 UTC
